blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/pdubbbbbs/proxmox-helper-script/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://github.com/pdubbbbbs/proxmox-helper-script/tree/master/docs
    about: Be sure to check the documentation first.
