name: Cross-Platform Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sundays

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        powershell: ['7.2', '7.3']
        include:
          - os: windows-latest
            powershell: '5.1'

    steps:
      - uses: actions/checkout@v5

      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          powershell-version: ${{ matrix.powershell }}
        if: matrix.powershell != '5.1'

      - name: Install dependencies
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Pester -MinimumVersion 5.0.0 -Force
          Install-Module -Name PSScriptAnalyzer -Force

      - name: Run tests
        shell: pwsh
        run: |
          $config = @{
            Run = @{
              Path = './tests'
              PassThru = $true
            }
            TestResult = @{
              Enabled = $true
              OutputFormat = 'NUnitXml'
              OutputPath = "./TestResults-${{ matrix.os }}-${{ matrix.powershell }}.xml"
            }
          }
          
          $result = Invoke-Pester -Configuration $config
          if ($result.FailedCount -gt 0) {
            throw "$($result.FailedCount) tests failed."
          }

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.os }}-${{ matrix.powershell }}
          path: TestResults-*.xml

