name: PowerShell Test and Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name PSScriptAnalyzer -Force
          
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path . -Recurse -Settings PSGallery
          
      - name: Run Tests
        shell: pwsh
        run: |
          if (Test-Path ./tests) {
            Invoke-Pester ./tests -PassThru
          }
